name: Linting etc
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  pull_request:
jobs:
  linting-etc:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: |
          echo "hi"
      